### ISSUE TITLE
Make outline more visually grepping

### ISSUE THREAD

**Issue by werunom** [mangecoeur/document-outline#61] opened 2018-01-31 04:59 UTC
Thanks for this lovely package! After using it for a while, felt of suggesting few things. 

1. Can the current section be made more visible?
Currently, there are thin boxes demarcating the larger section/sub-section within which the cursor is present. That works fine for me and makes sense - they are subtle and not too attention grabbing. But felt, the current subsection can be made more visually grepping. For instance, see the screenshot below - 

![screenshot_20180130_063815](https://user-images.githubusercontent.com/24664855/35605767-edfd65b2-0670-11e8-84b5-d9ff05b8c523.png)
In this, the cursor position is in a sub-section called `Duality and equivalence`. The thin box around is not that immediately visible. Can it be highlighted or made bold,etc.?

2. The arrow-head and bullet-point in the outline are disproportionate
The indent symbols for folded and non-folded headings at present are arrow-head and bullet-points. But as you can see in the screenshot, the arrow-head is much bigger in size than bullet-point. Can this creased out?

Let me know what you think of these. Thanks!

**Comment by mangecoeur** [comment] 2018-02-09 11:07
Hey thanks for the suggestions. You are right that it could be clearer - the issue is to make this work across a range of light/dark themes, which is frankly quite a boring job so i've been putting it off :P

**Comment by werunom** [comment] 2018-02-09 11:36
I can understand making it work across themes can be challenging. For instance, just to see how the outline appears, I tried few themes, and then I noticed - in every theme the box and the current section gets highlighted differently. 

In any case, thought making the current section bold might be a way out.

**Comment by mangecoeur** [comment] 2018-02-11 12:59
@werunom I changed the outline to follow the syntax style instead of the UI style, similar to how it is done in the atom-ide outline by facebook. This seems to make it work better with a variety of themes. I also added a bold highlight to the current heading. Closing this issue as a result.

**Closed by mangecoeur** 2018-02-11 12:59 UTC

**Comment by werunom** [comment] 2018-02-11 14:38
Thanks for taking time to implement this!
